name: Node.js CI/CD

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Check out repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Run linting
    - name: Run ESLint
      run: npm run lint

    # Run tests
    - name: Run tests
      run: npm test

    # Build step
    - name: Build
      run: npm run build

    # Security audit
    - name: Security audit
      run: npm audit --production

  # Optional deployment job (commented out by default)
  # deploy:
  #   needs: build-and-test
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to production
  #       # Add deployment steps here, e.g.:
  #       # - Deploy to Heroku
  #       # - Deploy to AWS ECS
  #       # - Deploy to DigitalOcean App Platform
  #       run: echo "Deployment would happen here"